[_this,"bravo",true,true,false,true,false] call cScripts_fnc_doStarterCrate;
[_this, "Squad Leader", "Cav_B_C_SquadLeader_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
[_this, "Fireteam Leader", "Cav_B_C_FireTeamLeader_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
[_this, "Automatic Rifleman", "Cav_B_C_AutomaticRifleman_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
[_this, "Grenadier", "Cav_B_C_Grenadier_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
[_this, "Rifleman", "Cav_B_C_Rifleman_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
[_this, "Combat Life Saver", "Cav_B_C_CombatLifeSaver_F","",["ACE_MainActions","cScriptQuickSelectionMenu"],"",false] call cScripts_fnc_addQuickSelection;
_this addMagazineCargoGlobal ["rhsusf_200Rnd_556x45_soft_pouch",250];
[_this, "rhs_weap_m240B",5] call CBA_fnc_removeWeaponCargo;
[_this, "tf47_m3maaws",10] call CBA_fnc_removeWeaponCargo;
[_this, "ACE_M84",50] call CBA_fnc_removeMagazineCargo;
[_this, "SatchelCharge_Remote_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "DemoCharge_Remote_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "ClaymoreDirectionalMine_Remote_Mag",50]; call CBA_fnc_removeMagazineCargo;
[_this, "APERSMine_Range_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "APERSMineDispenser_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "APERSBoundingMine_Range_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "SLAMDirectionalMine_Wire_Mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "rhs_mine_M19_mag",50] call CBA_fnc_removeMagazineCargo;
[_this, "ACE_CableTie",100] call CBA_fnc_removeItemCargo;